services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}    
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    networks:
      - winebar4-net

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #   PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT_INTERNAL}    
    ports:
      - "${PGADMIN_LISTEN_PORT_EXTERNAL}:${PGADMIN_LISTEN_PORT_INTERNAL}"
    depends_on:
      - postgres
    networks:
      - winebar4-net

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context:
        ./backend
    expose:
      - ${BACKEND_INTERNAL_PORT}
    env_file:
      - .env
    volumes:
      - ./backend/app:/app
    command: uvicorn sql_app.main:app --host 0.0.0.0 --port BACKEND_INTERNAL_PORT --root-path /backend --forwarded-allow-ips * --proxy-headers --reload
    restart: on-failure
    networks:
      - winebar4-net    

  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build: 
      context:
        ./winebar-4-frontend/frontend
    expose:
      - ${FRONTEND_INTERNAL_PORT}
    volumes:
      - ./winebar-4-frontend/frontend/src:/app/src
      - ./winebar-4-frontend/frontend/public:/app/public
      - ./winebar-4-frontend/frontend/tsconfig.json:/app/tsconfig.json
    command: npm start
    networks:
      - winebar4-net
    env_file:
      - .env

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: ./nginx
    ports:
      - ${NGINX_INTERNAL_PORT}:${NGINX_EXTERNAL_PORT}
    depends_on:
      - backend
      - frontend
    networks:
      - winebar4-net
    restart: on-failure
    environment:
      - 
      - BACKEND_CONTAINER_NAME: ${BACKEND_CONTAINER_NAME}
      - FRONTEND_CONTAINER_NAME: ${FRONTEND_CONTAINER_NAME}

  servidor-claves:
    container_name: ${SERVIDOR_CLAVES_CONTAINER_NAME}
    build:
      context: ./winebar-servidor-claves
      
    expose:
      - ${SERVIDOR_CLAVES_PORT}
    env_file:
      - .env
    environment:
      - API_KEY_TERMINAL_ADMIN=${API_KEY_TERMINAL_ADMIN}
    command: uvicorn main:app --host 0.0.0.0 --port ${SERVIDOR_CLAVES_PORT} --reload
    ports:
      - ${SERVIDOR_CLAVES_PORT}:${SERVIDOR_CLAVES_PORT}
    networks:
      - winebar4-net

networks:
  winebar4-net: 
    driver: bridge

