services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      - winebar-app_network

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT_INTERNAL}    
    ports:
      - "${PGADMIN_LISTEN_PORT_EXTERNAL}:${PGADMIN_LISTEN_PORT_INTERNAL}"
    depends_on:
      - postgres
    networks:
      - winebar-app_network

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context:
        ./backend
    expose:
      - ${BACKEND_INTERNAL_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=${POSTGRES_CONTAINER_NAME}
    volumes:
      - ./backend/app:/app
    depends_on:
      - postgres
      - nginx
    command: uvicorn sql_app.main:app --host 0.0.0.0 --port ${BACKEND_INTERNAL_PORT} --root-path /backend --forwarded-allow-ips * --proxy-headers --reload
    restart: on-failure
    networks:
      - winebar-app_network    

  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build: 
      context:
        ./winebar-4-frontend/frontend
    expose:
      - ${FRONTEND_INTERNAL_PORT}
    volumes:
      - ./winebar-4-frontend/frontend/src:/app/src
      - ./winebar-4-frontend/frontend/public:/app/public
      - ./winebar-4-frontend/frontend/tsconfig.json:/app/tsconfig.json
    command: npm start
    networks:
      - winebar-app_network
    environment:
      - PORT=${FRONTEND_INTERNAL_PORT}
      - REACT_APP_SERVIDOR_CLAVES_PORT=${SERVIDOR_CLAVES_PORT}
      - REACT_APP_BACKEND_INTERNAL_PORT=${BACKEND_INTERNAL_PORT}
      - REACT_APP_NGINX_PORT=${NGINX_INTERNAL_PORT}

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: ./nginx
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    # depends_on:
    #   - backend
    #   - frontend
    networks:
      - winebar-app_network
    restart: on-failure
    environment:
      - NGINX_INTERNAL_PORT=${NGINX_INTERNAL_PORT}
      - BACKEND_CONTAINER_NAME=${BACKEND_CONTAINER_NAME}
      - FRONTEND_CONTAINER_NAME=${FRONTEND_CONTAINER_NAME}
      - FRONTEND_INTERNAL_PORT=${FRONTEND_INTERNAL_PORT}
      - BACKEND_INTERNAL_PORT=${BACKEND_INTERNAL_PORT}

  servidor-claves:
    container_name: ${SERVIDOR_CLAVES_CONTAINER_NAME}
    build:
      context: ./winebar-servidor-claves      
    expose:
      - ${SERVIDOR_CLAVES_PORT}
    environment:
      - API_KEY_TERMINAL_ADMIN=${API_KEY_TERMINAL_ADMIN}
    command: uvicorn main:app --host 0.0.0.0 --port ${SERVIDOR_CLAVES_PORT} --reload
    ports:
      - ${SERVIDOR_CLAVES_PORT}:${SERVIDOR_CLAVES_PORT}
    networks:
      - winebar-app_network

networks:
  winebar-app_network: 
    driver: bridge

