services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    env_file:
      - .env
    # environment:
    # these env vars are used for postgres image
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}    
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #   PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT_INTERNAL}    
    ports:
      - "${PGADMIN_LISTEN_PORT_EXTERNAL}:${PGADMIN_LISTEN_PORT_INTERNAL}"
    depends_on:
      - postgres

  servidor-claves:
    container_name: ${SERVIDOR_CLAVES_CONTAINER_NAME}
    build:
      context: ./winebar-servidor-claves      
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - API_KEY_TERMINAL_ADMIN=${API_KEY_TERMINAL_ADMIN}
    volumes:
      - ./winebar-servidor-claves:/app
    command: uvicorn main:app --host 0.0.0.0 --port 3001 --reload
    ports:
      - "3001:3001"