services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    env_file:
      - .env
    # environment:
    # - POSTGRES_SERVER=localhost
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}    
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #   PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT_INTERNAL}    
    ports:
      - "${PGADMIN_LISTEN_PORT_EXTERNAL}:${PGADMIN_LISTEN_PORT_INTERNAL}"
    depends_on:
      - postgres

  servidor-claves:
    container_name: ${SERVIDOR_CLAVES_CONTAINER_NAME}
    build:
      context: ./winebar-servidor-claves      
    expose:
      - ${SERVIDOR_CLAVES_PORT}
    env_file:
      - .env
    environment:
      - API_KEY_TERMINAL_ADMIN=${API_KEY_TERMINAL_ADMIN}
    command: uvicorn main:app --host 0.0.0.0 --port ${SERVIDOR_CLAVES_PORT} --reload
    ports:
      - ${SERVIDOR_CLAVES_PORT}:${SERVIDOR_CLAVES_PORT}