"""empty message

Revision ID: 16e967fead9e
Revises: 4269c6cef008
Create Date: 2024-04-06 14:22:52.637720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e967fead9e'
down_revision: Union[str, None] = '4269c6cef008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the columns as nullable
    op.add_column('ordenes', sa.Column('monto_cobrado_efectivo', sa.Float(), nullable=True))
    op.add_column('ordenes', sa.Column('monto_cobrado_tarjeta', sa.Float(), nullable=True))
    op.add_column('ordenes', sa.Column('monto_cobrado_transferencia', sa.Float(), nullable=True))

    # Step 2: Populate existing records with a default value
    op.execute('UPDATE ordenes SET monto_cobrado_efectivo = 0.0 WHERE monto_cobrado_efectivo IS NULL')
    op.execute('UPDATE ordenes SET monto_cobrado_tarjeta = 0.0 WHERE monto_cobrado_tarjeta IS NULL')
    op.execute('UPDATE ordenes SET monto_cobrado_transferencia = 0.0 WHERE monto_cobrado_transferencia IS NULL')

    # Step 3: Alter the column to non-nullable
    op.alter_column('ordenes', 'monto_cobrado_efectivo', nullable=False)
    op.alter_column('ordenes', 'monto_cobrado_tarjeta', nullable=False)
    op.alter_column('ordenes', 'monto_cobrado_transferencia', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes', 'monto_cobrado_transferencia')
    op.drop_column('ordenes', 'monto_cobrado_tarjeta')
    op.drop_column('ordenes', 'monto_cobrado_efectivo')
    # ### end Alembic commands ###
