"""empty message

Revision ID: 17b5a07986c8
Revises: 22d361e30f54
Create Date: 2024-02-24 18:41:47.931977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17b5a07986c8'
down_revision: Union[str, None] = '22d361e30f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vinos', sa.Column('id_vitte', sa.String(), nullable=True))
    op.drop_column('vinos', 'ultima_sincronizacion')
    op.drop_column('vinos', 'listado_metadatos')
    op.drop_column('vinos', 'listado_precios_sugeridos')
    op.drop_column('vinos', 'listado_nombres')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vinos', sa.Column('listado_nombres', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vinos', sa.Column('listado_precios_sugeridos', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vinos', sa.Column('listado_metadatos', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vinos', sa.Column('ultima_sincronizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('vinos', 'id_vitte')
    # ### end Alembic commands ###
