"""empty message

Revision ID: 214416e7b8ba
Revises: 5c77e42e089e
Create Date: 2024-04-28 15:49:12.290665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214416e7b8ba'
down_revision: Union[str, None] = '5c77e42e089e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vinos', sa.Column('volumen', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vinos', 'volumen')
    # ### end Alembic commands ###
