"""resto de tarjetas y usuarios

Revision ID: 240abe5a681d
Revises: c8ea15992030
Create Date: 2024-02-13 01:14:25.794049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240abe5a681d'
down_revision: Union[str, None] = 'c8ea15992030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_interno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente_detalles_adicionales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('dni', sa.Integer(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('teléfono', sa.String(), nullable=True),
    sa.Column('domicilio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_y_tarjetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('tarjeta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tarjeta'], ['tarjetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_interno_y_tarjetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_personal_interno', sa.Integer(), nullable=True),
    sa.Column('tarjeta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personal_interno'], ['personal_interno.id'], ),
    sa.ForeignKeyConstraint(['tarjeta'], ['tarjetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_interno_y_tarjetas')
    op.drop_table('clientes_y_tarjetas')
    op.drop_table('cliente_detalles_adicionales')
    op.drop_table('personal_interno')
    op.drop_table('clientes')
    # ### end Alembic commands ###
