"""empty message

Revision ID: 2d35372d465c
Revises: d4663c9448b0
Create Date: 2024-03-23 17:07:03.622420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d35372d465c'
down_revision: Union[str, None] = 'd4663c9448b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('monto_cargado', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'monto_cargado')
    # ### end Alembic commands ###
