"""empty message

Revision ID: 36971ac2689d
Revises: c6b5aea66268
Create Date: 2024-05-03 19:56:29.414234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36971ac2689d'
down_revision: Union[str, None] = 'c6b5aea66268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectorestapas', sa.Column('nombre_terminal', sa.String(), nullable=False))
    op.drop_column('lectorestapas', 'id_terminal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectorestapas', sa.Column('id_terminal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('lectorestapas', 'nombre_terminal')
    # ### end Alembic commands ###
