"""cambio activo por activa

Revision ID: 36e7db46377d
Revises: d07203a024cf
Create Date: 2024-02-14 20:03:15.499497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e7db46377d'
down_revision: Union[str, None] = 'd07203a024cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'activo', new_column_name='activa', existing_type=sa.Boolean())
    op.alter_column('personal_interno', 'activo', new_column_name='activa', existing_type=sa.Boolean())
    op.alter_column('productos', 'activo', new_column_name='activa', existing_type=sa.Boolean())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'activa', new_column_name='activo', existing_type=sa.Boolean())
    op.alter_column('personal_interno', 'activa', new_column_name='activo', existing_type=sa.Boolean())
    op.alter_column('productos', 'activa', new_column_name='activo', existing_type=sa.Boolean())
    # ### end Alembic commands ###
