"""empty message

Revision ID: 3bb1f78da096
Revises: 445d90cf1bd0
Create Date: 2024-02-26 16:21:54.591765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb1f78da096'
down_revision: Union[str, None] = '445d90cf1bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'promocion_aplicada')
    op.add_column('renglones', sa.Column('promocion_aplicada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renglones', 'promocion_aplicada')
    op.add_column('pedidos', sa.Column('promocion_aplicada', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
