"""empty message

Revision ID: 4269c6cef008
Revises: e85d6ec8b500
Create Date: 2024-03-29 13:08:37.288817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4269c6cef008'
down_revision: Union[str, None] = 'e85d6ec8b500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('rol_usado_nombre', sa.String(), nullable=True))
    
    # Set all rows in the column to "CLIENTE_ESTANDAR"
    op.execute("UPDATE clientes SET rol_usado_nombre = 'CLIENTE_ESTANDAR'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'rol_usado_nombre')
    # ### end Alembic commands ###
