"""empty message

Revision ID: 5c77e42e089e
Revises: 16e967fead9e
Create Date: 2024-04-06 15:13:43.560108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c77e42e089e'
down_revision: Union[str, None] = '16e967fead9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('comentarios', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes', 'comentarios')
    # ### end Alembic commands ###
