"""empty message

Revision ID: 75c679b9e18d
Revises: 214416e7b8ba
Create Date: 2024-04-28 15:58:30.919231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c679b9e18d'
down_revision: Union[str, None] = '214416e7b8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renglones', sa.Column('vitte_consumo_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renglones', 'vitte_consumo_id')
    # ### end Alembic commands ###
