"""empty message

Revision ID: 8143854ecdea
Revises: d38397a06196
Create Date: 2024-06-09 03:23:31.156614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8143854ecdea'
down_revision: Union[str, None] = 'd38397a06196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the columns as nullable
    op.add_column('ordenes', sa.Column('monto_maximo_pedido', sa.Float(), nullable=True))
    
    # Step 2: Populate existing records with a default value
    op.execute('UPDATE ordenes SET monto_maximo_pedido = 100000.0 WHERE monto_maximo_pedido IS NULL')
    
    # Step 3: Alter the column to non-nullable
    op.alter_column('ordenes', 'monto_maximo_pedido', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes', 'monto_maximo_pedido')
    # ### end Alembic commands ###
