"""empty message

Revision ID: 8ed8d67104b9
Revises: 3bb1f78da096
Create Date: 2024-02-28 15:39:33.420496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed8d67104b9'
down_revision: Union[str, None] = '3bb1f78da096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('cerrado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'cerrado')
    # ### end Alembic commands ###
