"""paso tarjeta_id a personal_interno

Revision ID: d07203a024cf
Revises: 42c7832b8203
Create Date: 2024-02-14 16:11:03.925721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07203a024cf'
down_revision: Union[str, None] = '42c7832b8203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_interno_y_tarjetas')
    op.add_column('personal_interno', sa.Column('tarjeta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'personal_interno', 'tarjetas', ['tarjeta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_interno', type_='foreignkey')
    op.drop_column('personal_interno', 'tarjeta_id')
    op.create_table('personal_interno_y_tarjetas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_personal_interno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tarjeta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_personal_interno'], ['personal_interno.id'], name='personal_interno_y_tarjetas_id_personal_interno_fkey'),
    sa.ForeignKeyConstraint(['tarjeta'], ['tarjetas.id'], name='personal_interno_y_tarjetas_tarjeta_fkey'),
    sa.PrimaryKeyConstraint('id', name='personal_interno_y_tarjetas_pkey')
    )
    # ### end Alembic commands ###
