"""empty message

Revision ID: d4663c9448b0
Revises: 4aa9b333c540
Create Date: 2024-03-21 01:03:31.326849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4663c9448b0'
down_revision: Union[str, None] = '4aa9b333c540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the column as nullable
    op.add_column('ordenes', sa.Column('monto_cargado', sa.Float(), nullable=True))

    # Step 2: Populate existing records with a default value
    op.execute('UPDATE ordenes SET monto_cargado = 0.0 WHERE monto_cargado IS NULL')

    # Step 3: Alter the column to non-nullable
    op.alter_column('ordenes', 'monto_cargado', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes', 'monto_cargado')
    # ### end Alembic commands ###
