"""empty message

Revision ID: d8cf9fa75d47
Revises: 8143854ecdea
Create Date: 2024-06-30 04:00:27.808470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cf9fa75d47'
down_revision: Union[str, None] = '8143854ecdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes', sa.Column('monto_cargado_fudo', sa.Float(), nullable=True))
    op.add_column('pedidos', sa.Column('exportado_fudo', sa.Boolean(), nullable=True))

    op.execute('UPDATE ordenes SET monto_cargado_fudo = 0.0 WHERE cerrada_por IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'exportado_fudo')
    op.drop_column('ordenes', 'monto_cargado_fudo')
    # ### end Alembic commands ###
