"""empty message

Revision ID: e85d6ec8b500
Revises: 2d35372d465c
Create Date: 2024-03-28 19:49:26.445842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85d6ec8b500'
down_revision: Union[str, None] = '2d35372d465c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turnos', sa.Column('comentarios', sa.Text(), nullable=True))
    op.alter_column('turnos', 'ingresos_totales', new_column_name='monto_en_caja', existing_type=sa.Float())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turnos', 'monto_en_caja', new_column_name='ingresos_totales', existing_type=sa.Float())
    op.drop_column('turnos', 'comentarios')
    # ### end Alembic commands ###
